Repository anitab-org/stem-diverse-tv, pull requests merged in 2021-04, with the labels that each got.

#166 Removed table of contents from Readme
  README.md
Labels: Status: Ready to Merge

#189 chore: setup all-contributors bot
  .all-contributorsrc
  README.md
Labels: Status: Needs Review

#222 added badge and link
  README.md
Labels: Category: Documentation/Training, Open Source Hack, Status: Ready to Merge

#218 fix: Docusauras editUrl
  docusaurus.config.js
Labels: Category: Documentation/Training, Open Source Hack, Status: Ready to Merge

#219 Removed the redundancy of headings in Readme file
  README.md
Labels: Status: Ready to Merge

#169 Update Clone Instructions in readme file
  README.md
Labels: Open Source Hack, Status: Ready to Merge

#225 Docs: Update the documentation of the project on Docusauras, fixes issue #217
  docusaurus.config.js
  src/pages/index.js
Labels: Open Source Hack, Status: Needs Testing
